agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

backoffice_base:
    resource: "@BackofficeBaseBundle/Resources/config/routing.yml"
    prefix:   /admin

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
