agenda_evenement:
    resource: "@AgendaBundle/Controller/EvenementController.php"
    type:     annotation

agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

backoffice_base:
    resource: "@BackofficeBaseBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
