evenement_index:
    path:  /
    defaults: {_controller: AgendaBundle:Evenement:index}

evenement_new:
    path:  /new
    defaults: {_controller: AgendaBundle:Evenement:new}

evenement_show:
    path:  /{id}
    defaults: {_controller: AgendaBundle:Evenement:show}

evenement_new_suite:
    path: /{id}/new/suite
    defaults: {_controller: AgendaBundle:Evenement:SuiteNew}

evenement_delete:
    path: /annuler/{id}
    defaults: {_controller: AgendaBundle:Evenement:delete}

evenement_reactivate:
    path: /supprimer/{id}
    defaults: {_controller: AgendaBundle:Evenement:reactivate}

evenement_edit:
    path: /{id}/edit
    defaults: {_controller: AgendaBundle:Evenement:edit}

evenement_edit_suite:
    path: /{id}/edit/suite
    defaults: {_controller: AgendaBundle:Evenement:suiteEdit}

evenement_export:
    path: /{id}/export
    defaults: {_controller: AgendaBundle:Evenement:export}
